Adding USB Support for dive computers
DiveNote/dive_computer pull request #2
Opened 2024-01-29 14:24 UTC by Ben1980

2024-01-29 15:14 UTC, Ben1980 commented
Oh was ist denn hier passiert?

2024-02-15 08:59 UTC, Sese-Schneider requested changes
Some small things you could optimize.
In general I love this! Great work and thank you so much 🚀

2024-02-15 08:59 UTC, Sese-Schneider commented on example/macos/Runner/Info.plist
> +    <string>Your explanation here</string>
Formatting
```suggestion
        <string>Your explanation here</string>
```

2024-02-15 08:59 UTC, Sese-Schneider commented on lib/framework/interfaces/dive_computer_interfaces.dart
> +        return _connectUsbHid(computer);
Do you now know the difference between the USB and USBHID in `libdivecomputer`?

2024-02-15 08:59 UTC, Sese-Schneider commented on macos/Classes/hid.c
is this file still required, now that you've removed all others?

2024-02-15 10:31 UTC, Sese-Schneider reviewed
Had to leave for work, here's my finalized review

2024-02-15 10:31 UTC, Sese-Schneider commented on src/CMakeLists.txt
> +  OUTPUT_NAME "libdivecomputer"
Why does the output name need to be `libdivecomputer`?

2024-02-15 10:31 UTC, Sese-Schneider commented on src/CMakeLists.txt
> +# add_compile_definitions(HAVE_PTHREAD_H=1)
Can this be removed?

2024-02-15 10:31 UTC, Sese-Schneider commented on pubspec.yaml
> +  ffigen: ^9.0.0
Why are you downgrading ffigen?

2024-02-15 10:31 UTC, Sese-Schneider commented on pubspec.yaml
Is there a reason you're fixing the constraints to specific versions here?

2024-02-20 18:03 UTC, Ben1980 commented
@Sese-Schneider I think we should discuss if this PR can be merged or how changes should look like. Shall we have a call?

2024-02-22 08:24 UTC, Sese-Schneider commented
@Ben1980 PR looks very good so far - I want to test it myself after the weekend and merge it ASAP.
I also want to give Windows another try later.
Nevertheless, I try to get it to main and publish this version hopefully soon.
If I have more questions we can call, or if you want to anyways to talk about it send me an invite please 👍🏼

2024-02-28 09:40 UTC, Sese-Schneider commented
merging to develop - windows is still not working so this would be my next step to get it to main.
I will publish this as `v0.1.0-dev.1`

2024-02-28 09:57 UTC, merged